NightOwlV3.1/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :messages do 
  	resources :comments
  end
  root 'messages#index'
  get 'about/index'
end

NightOwlV3.1/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

NightOwlV3.1/app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	def to_param
		"#{id} #{title}".parameterize
	end
	
end

NightOwlV3.1/app/models/user.rb
class User < ActiveRecord::Base
    
	has_many :messages
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:facebook, :twitter]
         
         
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
        end
    end
end

NightOwlV3.1/app/controllers/about_controller.rb
class AboutController < ApplicationController
    
    def index
    end
end

NightOwlV3.1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  
end

NightOwlV3.1/app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    # def facebook
    #     @user = User.from_omniauth(request.env["omniauth.auth"])
    #     sign_in_and_redirect @user
    # end
    
    
    # def twitter
    #     @user = User.from_omniauth(request.env["omniauth.auth"])
    #     sign_in_and_redirect @user
    # end
    
    # def github
    #     @user = User.from_omniauth(request.env["omniauth.auth"])
    #     sign_in_and_redirect @user
    # end
    
    
    def all
        # debugger
        user = User.from_omniauth(request.env["omniauth.auth"])
        if user.persisted?
            flash.notice = "You are signed in successfully with #{user.provider}!"
            sign_in_and_redirect user
        else
            session["devise.user_attributes"] = user.attributes
            redirect_to new_user_registration_url
        end
        
    end
    alias_method :facebook, :all
    alias_method :twitter, :all
    # alias_method :twitter, :all
    # alias_method :github, :all
    # alias_method :digitalocean, :all
end

NightOwlV3.1/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]

	def create
		# creates a comment with respect to the message
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
	end

	private

		def comment_params
			params.require(:comment).permit(:content)
		end

		def find_message
			@message = Message.find(params[:message_id])
		end

		def find_comment
			@comment = @message.comments.find(params[:id])
		end

end

NightOwlV3.1/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy]

	def index
		@messages = Message.all.order("created_at DESC")
		@messages = Message.where(["title LIKE ?","%#{params[:search]}%"])
	end

	def show
	end

	def new
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to root_path
	end

	private
		def message_params
			params.require(:message).permit(:title, :location, :description)
		end

		def find_message
			@message = Message.find(params[:id])
		end
		
	

		

end

NightOwlV3.1/app/helpers/about_helper.rb
module AboutHelper
end

NightOwlV3.1/app/helpers/application_helper.rb
module ApplicationHelper
end

NightOwlV3.1/app/helpers/comments_helper.rb
module CommentsHelper
end

NightOwlV3.1/app/helpers/messages_helper.rb
module MessagesHelper
end

NightOwlV3.1/app/views/about/index.html.erb
<body class="aboutImg">
<center><h1 style="color:red">What is Night Owl?</h1></center>
<h2>Are You a <strong>Night Owl</strong>?</h2>
This is a site where you can look up classes where other people need help with or have questions on certain materials. </br>
    You all can schedule time and place where you would like to meet.


Testing from Tien

</body>

NightOwlV3.1/app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
	<% if user_signed_in? %>
		<% if comment.user_id == current_user.id %>
			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
			<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	<% end %>
	</div>
</div>

NightOwlV3.1/app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: "Message" %>
	<%= f.submit "Reply", :class => 'btn-custom' %>
<% end %>

NightOwlV3.1/app/views/comments/edit.html.erb
<h1>Edit Message</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
	<%= f.input :content, label: "Message" %>
	<%= f.submit "Update Message" %>
<% end %>

NightOwlV3.1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Night Owl</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= image_tag("owl-logo-2.png", width: '50px', height: '55px', :alt =>"walk")%>

				<strong><%= link_to "Group List", root_path, class: "navbar-brand" %></strong>
				<%= form_tag messages_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %>
				<%= submit_tag "Search" %>
			</div>
			
			
			<% if user_signed_in? %>
				<% if current_user.admin? %>
					<nav class='dashboard_root_link'><a class="pjax" href="/admin/">Admin Dashboard</a></nav>
				<% end %>
				<p>
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-text navbar-link navbar-right" %>
				<%= link_to "Create New Group", new_message_path, class: "navbar-text navbar-link navbar-right" %>
				<%= link_to current_user.email, edit_user_registration_path, class: "navbar-text navbar-link navbar-right" %>
				</p>
				<% else %>
					<p><%= link_to "Sign Up", new_user_registration_path, class: "navbar-text navbar-link navbar-right" %>
					<%= link_to "Log In", new_user_session_path, class: "navbar-text navbar-link navbar-right" %>
					<%= link_to "About us", about_index_path, class: "navbar-text navbar-link navbar-right" %></p>
				<% end %>
			<% end %>
		</div>
	</nav>

	<!--<p class="notice"><%= notice %></p>-->
	<!--<p class="alert"><%= alert %></p>-->
	
	
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

NightOwlV3.1/app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "Group Title" %>
	<%= f.input :location, label: "Location" %>
	<%= f.input :description, label: "Description" %>
	
	
	<% if request.path == new_message_path %>
		<%= f.submit "Create Group"%>
	<% else %>
		<%= f.submit "Update Group"%>
	<% end %>
<% end %>

NightOwlV3.1/app/views/messages/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form' %>

NightOwlV3.1/app/views/messages/index.html.erb
<% @messages.each do |message| %>
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title">Group: <%= message.title %></h2>
			<h2 class="message-locat">Location: <%= message.location %></h2>
			<h2 class="message-tim">Created: <%= time_ago_in_words(message.created_at) %> ago</h2>

			<%= link_to "View Message", message, class: "btn-custom" %></br>
			 <!--message.location-->
		</div>
	</div>
	
	
	
<% end %>






<!--<center> < image_tag("study-sess.jpg", :alt => "study sess </center>-->

NightOwlV3.1/app/views/messages/new.html.erb
<body class="logInImg">
<div class="col-md-8 col-md-offset-2">
	<h1 class="new-msg-header">New Group</h1>
	<%= render 'form' %>
</div>
</body>

NightOwlV3.1/app/views/messages/show.html.erb
<body class="studyImage2">
	
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-location"> Location: <%= @message.location %> </p>
		<p class="message-desc">Description: </br><%= @message.description %></p>

		<!-- Add a Posted By: username at timestamp. -->

		<h3 class="comment-section-header">Messages:</h3>
		<!-- renders the _comment.html.erb partial file. -->
		<p><%= render @message.comments %></p>
	<% if user_signed_in? %>
		<h3 class="reply-to-msg">Reply to Message:</h3>
		<!-- renders the comments form -->
		<%= render 'comments/form' %>

		<% else %>
			<%="Please sign in to reply."%></br>
			<%= link_to "Sign in", new_user_session_path %>
	<% end %></br>


		<!-- Add a conditional so that the 'edit' and 'destroy' links only appear for the user who created the message. -->
		<div class="links btn-group">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
		<% if user_signed_in? %>
			<% if @message.user_id == current_user.id %>
				<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
				<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
			<% end %>
		<% end %>
		</div>
	</div>
</div>

</body>